name: check_64_to_32

on:
  push:
    paths-ignore:
      - .gitlab-ci.yml
  pull_request:
  release:
  schedule:
    - cron: '0 0 * * SUN'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
jobs:
  check:
    if: |
      github.event_name == 'schedule' ||
      (!contains(github.event.head_commit.message, 'ci skip'))
    runs-on: ubuntu-latest
    steps:
      - name: pkg cleanup
        run: |
          ./travis/pkg_cleanup.sh
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress:
          fetch-depth: 200
      - name: check
        run: |
          ./travis/check_64_to_32.sh
  



     
