name: nwchem_docker

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '59 15 * * FRI'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  docker_schedule:
    strategy:
        fail-fast: false
        matrix:
          folder:
            - nwchem-dev
          archs: [linux/amd64, linux/arm64, linux/ppc64le, linux/arm/v7]
          fc: [ gfortran, nvfortran]
          include:
            - {folder: nwchem-dev.xlf, archs: linux/ppc64le, fc: xlf}
          exclude:
            - {folder: nwchem-dev, archs: linux/ppc64le, fc: nvfortran}
            - {folder: nwchem-dev, archs: linux/arm/v7, fc: nvfortran}
    runs-on: ubuntu-latest
    timeout-minutes: 420
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'nwchemgit/nwchem-dockerfiles'
          fetch-depth: 5
      - name: Setup cache
        id: setup-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
          key: ${{ matrix.folder}}-${{ matrix.fc}}/${{ matrix.archs}}-nwchemcache-v016
      - name: Qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: crazymax/binfmt:v6.0.0
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: |
              image=moby/buildkit:master
      - name: Get Arch
        id: get-arch
        run: |
          echo "::set-output name=arch::$(echo ${{matrix.archs }} | sed 's/linux//'|sed  's/\///g' )"
        shell: bash
      - name: FC tag
        id: fc-tag
        run: |
          if [[ ${{ matrix.fc }} == 'gfortran'  ]]; then 
            echo "::set-output name=fc::"  
          else 
            echo "::set-output name=fc::$(echo -${{matrix.fc }}  )"  
          fi
        shell: bash
      - name: fetch cache
        if: (steps.setup-cache.outputs.cache-hit == 'true') && ( matrix.folder  != 'helloworld' )
        run: |
          cd ${{ matrix.folder }}
          if [[ -f ~/cache/libext.tar.bz2 ]]; then \
          echo "libext cache present" ; \
          mkdir -p cache|| true ; \
          rsync -av ~/cache/libext* cache/. ; \
          echo "libext cache fetched" ; \
          fi
      - name: build_schedule
        uses: docker/build-push-action@v2
        with:
          push: false
          context: ${{ matrix.folder }}
          platforms: ${{ matrix.archs }}
          build-args: |
            FC=${{ matrix.fc }}
      - name: store cache
        run: |
            mkdir -p ~/cache/
            docker run --privileged --user 0 --rm --platform ${{matrix.archs }} \
            --entrypoint='/bin/cp' -v ~/cache:/data \
            ghcr.io/${{ github.actor }}/${{ matrix.folder }}${{ steps.fc-tag.outputs.fc }}/${{ steps.get-arch.outputs.arch }} \
            -rp /opt/nwchem/src/libext/libext.tar.bz2 /data/.  || true
            ls -Ralrt ~/cache || true
