name: NWChem_CI_selfhosted

on:
  push:
    paths-ignore:
      - .gitlab-ci.yml
  pull_request:
  release:
  schedule:
    - cron: '0 0 * * SUN'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
jobs:
  build:
    if: |
      github.event_name == 'schedule' ||
      (!contains(github.event.head_commit.message, 'ci skip'))
    runs-on: self-hosted
    strategy:
      matrix:
        blas: [build_openblas]
        blas_size:
          - 8
        experimental: [false]
        armci_network:
          - MPI-TS
          - MPI-PR
        nwchem_modules:
          - "all python xtb"
        fc:
          - ifort
          - gfortran
        use_openmp:
          - 2
        use_simint:
          - 1
        use_libxc:
          - 1
        use_tblite:
          - 1
        build_plumed:
          - 1
        
      fail-fast: false
    env:
        ARMCI_NETWORK: ${{ matrix.armci_network }}
        NWCHEM_MODULES: ${{ matrix.nwchem_modules }}
        USE_SIMINT: ${{ matrix.use_simint }}
        USE_LIBXC: ${{ matrix.use_libxc }}
        USE_TBLITE: ${{ matrix.use_tblite }}
        BUILD_PLUMED: ${{ matrix.build_plumed }}
        FC: ${{ matrix.fc }}
        CC: ${{ matrix.cc }}
        COMEX_MAX_NB_OUTSTANDING: 4
        SIMINT_MAXAM: 4
        SIMINT_VECTOR: avx2
        BLAS_ENV:  ${{ matrix.blas }}
        BLAS_SIZE:  ${{ matrix.blas_size }}
        USE_OPENMP:  ${{ matrix.use_openmp }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 40
          clean: true
      - name: Get Instruction
        id: get-simd
        run: |
          echo "::set-output name=simd::$(./travis/guess_simd.sh)"
        shell: bash
      - name: Setup cache
        id: setup-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/cache
            ~/apps
          key: ${{ runner.os }}-${{ matrix.mpi_impl}}-${{ matrix.fc}}-xcode${{ matrix.xcode_version}}-simint${{ matrix.use_simint}}-blas${{ matrix.blas}}-blas_size${{ matrix.blas_size}}-libxc${{matrix.use_libxc}}-tblite${{matrix.use_tblite}}-simd${{ steps.get-simd.outputs.simd }}-nwchemcache-v003
      - name: fetch apps cache
        if: steps.setup-cache.outputs.cache-hit == 'true'
        run: |
          if [[ -f ~/apps/oneapi/setvars.sh ]]; then \
          echo "apps oneapi cache fetched" ; \
          export GOT_APPSCACHE="Y" ; fi
      - name: build environment
        run: |
          pwd
          ls -lart
          ./travis/build_env.sh
      - name: fetch cache
        if: steps.setup-cache.outputs.cache-hit == 'true'
        run: |
          ls -Rla ~/cache
          [ -d ~/cache/libext ] && rsync -av ~/cache/libext/* src/libext/.  
          [ -d ~/cache/simint/simint_install/lib ] && \
          mkdir -p src/NWints/simint/libsimint_source/simint_install && \
          rsync -av ~/cache/simint/simint_install/* src/NWints/simint/libsimint_source/simint_install/.   || true
          [ -f ~/cache/tarballs/dftd3.tgz ] && rsync -av ~/cache/tarballs/dftd3.tgz  src/nwpw/nwpwlib/nwpwxc/dftd3.tgz  || true
          echo "cache fetched"
      - name: compile
        id: compile
        run: |
          cc -v
          ./travis/config_nwchem.sh
          ./travis/compile_nwchem.sh
      - name: Check compilation result
        if: ${{ failure() }}
        run: |
          cat src/tools/build/config.log || true
          cat src/tools/build/comex/config.log || true
          tail -100 64log || true
      - name: store cache
        run: |
          mkdir -p ~/apps || true
          mkdir -p ~/cache/libext/lib  ~/cache/libext/bin  ~/cache/libext/include ~/cache/libext/mpich || true
          mkdir -p ~/cache/libext/mpich/mpich || true
          mkdir -p ~/cache/simint/simint_install || true
          mkdir -p ~/cache/tarballs || true
          ls -la src/libext ||true
          [ -d "src/libext/lib" ] && rsync -av src/libext/lib/*  ~/cache/libext/lib/. || true
          [ -d "src/libext/bin" ] && rsync -av src/libext/bin/*  ~/cache/libext/bin/. || true
          [ -d "src/libext/include" ] && rsync -av src/libext/include/*  ~/cache/libext/include/.  || true
          [ -d "src/NWints/simint/libsimint_source/simint_install/lib" ] && rsync -av src/NWints/simint/libsimint_source/simint_install/* ~/cache/simint/simint_install/.  || true
          [ -f "src/nwpw/nwpwlib/nwpwxc/dftd3.tgz" ] && rsync -av  src/nwpw/nwpwlib/nwpwxc/dftd3.tgz ~/cache/tarballs/dftd3.tgz || true
          echo "cache stored"
          ls -Rla ~/cache
      - name: qa_test
        id: qa_test
        if: steps.compile.conclusion == 'success'
        run: |
          source travis/nwchem.bashrc; cd QA && ./doafewqmtests.mpi 3
        shell: bash
      - name: Check if QA testing has failed
#        if: steps.qa_test.outcome == 'failure' || steps.qa_test.outcome == 'cancelled'
        if: ${{ failure() }} &&  steps.qa_test.outcome == 'failure'
        run: |
          echo "The steps context is:"
          echo "${{ toJson(steps) }}"
          echo "!!!!!!!!!!!!!!!!!!!!!!!!!"
          if [[ -f QA/testoutputs/dft_he2+.out ]]; then \
          grep d= QA/testoutputs/dft_he2+.out || true ;  fi
          if [[ -f QA/testoutputs/h2o_opt.out ]]; then \
          grep @ QA/testoutputs/h2o_opt.out || true ; fi
          if [[ -f QA/testoutputs/h2o2-response.out ]]; then \
          tail -490 QA/testoutputs/h2o2-response.out || true; fi
          if [[ -f QA/testoutputs/prop_mep_gcube.out ]]; then \
          tail -30 QA/testoutputs/prop_mep_gcube.out || true; fi
          if [[ -f QA/testoutputs/pspw.out ]]; then \
          tail -490 QA/testoutputs/pspw.out || true; fi
          if [[ -f QA/testoutputs/dft_smear.out ]]; then \
          grep @ QA/testoutputs/dft_smear.out || true; fi
          if [[ -f QA/testoutputs/dft_smear.out ]]; then \
          egrep d=  QA/testoutputs/dft_smear.out || true; fi
          if [[ -f QA/testoutputs/dft_smear.out ]]; then \
          tail -2000  QA/testoutputs/dft_smear.out || true; fi
          if [[ -f QA/testoutputs/ritddft_h2o.out ]]; then \
          tail -2000  QA/testoutputs/ritddft_h2o.out || true; fi
          if [[ -f QA/testoutputs/ritddft_co.out ]]; then \
          tail -2000  QA/testoutputs/ritddft_co.out || true; fi
          if [[ -f QA/testoutputs/pspw_md.out ]]; then \
          grep 'PSPW energy'  QA/testoutputs/pspw_md.out || true; fi
  



     
