name: Mirror and run GitLab CI

on:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  mirror_nwchemgit:
    runs-on: [ubuntu-18.04]
    fail-fast: true
    steps:
      - name: fetch and merge
        run: |
          git clone  --depth 30 git@github.com:edoapra/nwchem.git
          cd nwchem
          git config user.name "edoapra"
          git config user.email "edoardo.apra@gmail.com"
          git config pull.rebase false
          git remote add upstream https://github.com/nwchemgit/nwchem > /dev/null 2>&1
          git fetch origin
          git fetch upstream
          git merge upstream/master --no-edit
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
  mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/edoapra/nwchem"
      env:
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "edoapra"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "14461694"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
